### ISSUE TITLE
UX: Why not support for YubiKey NEO?

### ISSUE THREAD

**Issue by AnomalRoil** [str4d/age-plugin-yubikey#106]
## What were you trying to do
Setting up an age key on my YubiKey Neo.

## What happened
All want well until it asked me to touch the YK and failed (I've added the final response from my YK):
```
age-plugin-yubikey --generate --name 'YRO Yubi Neo - age'

Enter PIN for YubiKey with serial 4XXXXX8 (default is 123456): [hidden]
👆 Please touch the YubiKey
[TRACE yubikey::apdu] <<< Response { status_words: IncorrectSlotError, data: [] }
[ERROR yubikey::piv] failed to generate new key (incorrect slot)
Error: Error while communicating with YubiKey: key error
```

I finally found out [here](https://github.com/str4d/age-plugin-yubikey#manual-setup-and-technical-details), that the YK Neo is not supported.
But it still has PIV support, so I was wondering why? 
If it's just that it needed some customization and you didn't have one handy, I might be able to help.

**Comment by str4d** [comment]
YubiKey NEO is not supported because it is unsupported by the upstream `yubikey` crate. See https://github.com/iqlusioninc/yubikey.rs/issues/18 and https://github.com/iqlusioninc/yubikey.rs/pull/63 for details.
