### ISSUE TITLE
OpenBSD: ccid package needed for pcscd USB support

### ISSUE THREAD

**Issue by p0l1t1c1an** [str4d/age-plugin-yubikey#112]
## Environment
* OS: OpenBSD 7.2
* age-plugin-yubikey version: 0.3.2
* Yubikey 5C NFC

## What were you trying to do
Tried to generate new key using `age-plugin-yubikey` with no options for the interactive set-up.

## What happened
`age-plugin-yubikey` times out at asking to insert the yubikey as it does not detect when the yubikey is plugged in through USB:
```
⏳ Please insert the YubiKey you want to set up.
Error: Timed out while waiting for a YubiKey to be inserted.
```
pcscd gives the follow output in its log:
```
00000296 hotplug_libusb.c:147:HPReadBundleValues() Cannot open PC/SC drivers directory: /usr/local/lib/pcsc/drivers
00000069 hotplug_libusb.c:148:HPReadBundleValues() Disabling USB support for pcscd.
```
## Solution I found
Install the `ccid` package using pkg_add
This installs the needed drivers for pcscd to have USB support

## What I think could be done
* Update the Installation section of the Readme for OpenBSD to w/ the ccid package
* Check if other Unix-like OSes need ccid (or similar package) to be installed for USB support
* Note that ccid (or another package) may be needed on timeout

**Comment by mihaigalos** [comment]
Wouldn't using a dockerized version of this software directly work on OpenBSD?
[This](https://github.com/str4d/age-plugin-yubikey/pull/69) PR already proposed it.

**Comment by p0l1t1c1an** [comment]
No, that would not work. Docker does not run on OpenBSD. I think it's only for Linux. The closest thing I could do is run a VM with docker, but that is tedious and just annoying. 

My issue is with the lack of information on the README file regarding what I needed to install for OpenBSD, and proposing what I think would be useful information that would have prevented this issue or similar in the future.
