### ISSUE TITLE
UX: Default PIN the same as pin already setup for Yubikey Webauth or Authenticator?

### ISSUE THREAD

**Issue by mannp** [str4d/age-plugin-yubikey#125]
I have already set up my YubiKey key for Webauth or Authenticator, and they have separate pins assigned.

I seem to have wrongly tried those pins, and registering the age key failed twice already.

As I only have one try left, it is unclear if the Pin requested on first setup is purely for the age key setup, or in any way related to the webauthn or authenticator pins?

Thanks

**Comment by str4d** [comment]
WebAuthn uses the FIDO2 function of a YubiKey. This has a separately-configured PIN from the PIV applet used for SmartCard interfaces, which is what `age-plugin-yubikey` uses. See [this page](https://support.yubico.com/hc/en-us/articles/4402836718866-Understanding-YubiKey-PINs) for more details. I'll think about how I can improve the documentation or TUI labels to convey this.

I don't know what application you are referring to as "Authenticator". Do you mean the [Yubico Authenticator app](https://www.yubico.com/products/yubico-authenticator/)? If so, I'm unsure how you have separate PINs for WebAuthn and the authenticator, as both of these would use the FIDO2 function.

To confirm, you first tried the PIN you use for WebAuthn, and then you tried the PIN used for Authenticator, neither of which are what `age-plugin-yubikey` mentions as the default PIN (123456)?

My current guess is that you have changed the PIN for FIDO2 but have not changed the PIN for PIV, so using the default PIN of 123456 should work. However, before trying that, I would recommend that you check whether any key material is being stored on the YubiKey's PIV applet (so you know if it would be safe to reset the PIV applet). To do this:

- Install [YubiKey Manager](https://www.yubico.com/support/download/yubikey-manager/), run it, click "Applications", "PIV", and then "Configure Certificates". You will see four tabs you can click ("Authentication", "Digital Signature", "Key Management", and "Card Authentication"). If any of those tabs do not show "No certificate loaded" then there is data in the PIV applet.
- Run `age-plugin-yubikey` and selecting your Yubikey. The menu to select a slot should be displayed; if any slot does not say "Slot # (Empty)" then there is data in the PIV applet.

(This assumes that any keys generated or imported into the PIV applet also had a certificate imported and/or not deleted, but if a certificate isn't present then you have no other way to tell from the YubiKey what key material is in a slot, and if this were the case then I would expect whatever app you used to put keys in the PIV applet would have informed you of this.)

**Comment by mannp** [comment]
Thanks for the very detailed explanation and help 👍🏻 

Authenticator is from the new yico flutter authenticator, which shows Authenticator or Webauthn in the menu.

You are correct as it says it uses OATH, so I do have two passwords set for this and FIDO2 already.

All the PIV slots were showing as empty, so I used the default password and was able to configure the key correctly.

I was slow hitting the key to write the data too it and it timed out. Noting that my change in pin had been written, so rerunning the setup meant I had to use the new password.

All done, and thanks for creating the plugin :)

Before

ykman piv info
```
PIV version:              5.4.3
PIN tries remaining:      1/3
Management key algorithm: 3
WARNING: Using default PIN!
WARNING: Using default Management key!
CHUID: No data available
CCC:   No data available
```

After

ykman piv info                                                                                                                  
```
PIV version:              5.4.3
PIN tries remaining:      3/3
Management key algorithm: 3
Management key is stored on the YubiKey, protected by PIN.
CHUID: No data available
CCC:   No data available
Slot 82:
  Algorithm:   ECCP<r>
  Subject DN:  CN=<r>,OU=0.3.2,O=age-plugin-yubikey
  Issuer DN:   CN=<r>,OU=0.3.2,O=age-plugin-yubikey
  Serial: <r>      
  Fingerprint: <r>
  Not before:  2023-02-11T20:22:42
  Not after:   9999-12-31T23:59:59
```
