### ISSUE TITLE
Windows 10: cannot generate/store key, fails after pin

### ISSUE THREAD

**Issue by cpainchaud** [str4d/age-plugin-yubikey#135]
## Environment

* OS:
Windows 10 native
* age-plugin-yubikey version:
3.3 build with #129 
Yubikey 5a NFC Firmware: 5.4.3

## What were you trying to do
age-plugin-yubikey --generate
it seems to fail after I enter my pin

## What happened

```
Enter PIN for YubiKey with serial 23012069 (default is 123456): [hidden]
[TRACE yubikey::apdu] >>> Apdu { cla: 0, ins: Verify, p1: 0, p2: 128, data: [ <<this is my pin :D>>] }
[TRACE yubikey::transaction] >>> [0, 32, 0, 128, 8, <<this is my pin :D>>]
[TRACE yubikey::apdu] <<< Response { status_words: Success, data: [] }
[TRACE yubikey::transaction] going to send 5 bytes in this go
[TRACE yubikey::apdu] >>> Apdu { cla: 0, ins: GetData, p1: 63, p2: 255, data: [92, 3, 95, 193, 9] }
[TRACE yubikey::transaction] >>> [0, 203, 63, 255, 5, 92, 3, 95, 193, 9]
[TRACE yubikey::apdu] <<< Response { status_words: Success, data: [83, 28, 136, 26, 137, 24, <<24-byte MgmKey>>] }
[TRACE yubikey::apdu] >>> Apdu { cla: 0, ins: Authenticate, p1: 3, p2: 155, data: [124, 2, 128, 0] }
[TRACE yubikey::transaction] >>> [0, 135, 3, 155, 4, 124, 2, 128, 0]
[TRACE yubikey::apdu] <<< Response { status_words: IncorrectParamError, data: [] }
Error: Error while communicating with YubiKey: authentication error

```

Notes: it doesn't seem to decreate my PIN failed count

**Comment by str4d** [comment]
There were several in-flight improvements, including #129, that were blocked on a release of the `yubikey` crate. Now that `yubikey 0.8.0-pre.0` is published, I've merged #129. Could you please try using the current `main` branch and confirm whether you still encounter this issue?

**Comment by cpainchaud** [comment]
thank you for coming back to me, I will test and tell you

**Comment by str4d** [comment]
Okay, I've parsed out the last chunk of the trace and linked it to the relevant code sections:

https://github.com/str4d/age-plugin-yubikey/blob/22fd00bd22ee8a8fe9f3b33db2e4b7eea944bf37/src/builder.rs#L93-L96
https://github.com/str4d/age-plugin-yubikey/blob/22fd00bd22ee8a8fe9f3b33db2e4b7eea944bf37/src/key.rs#L307-L314
```
Enter PIN for YubiKey with serial 23012069 (default is 123456): [hidden]
```
https://github.com/str4d/age-plugin-yubikey/blob/22fd00bd22ee8a8fe9f3b33db2e4b7eea944bf37/src/key.rs#L315
```
[TRACE yubikey::apdu] >>> Apdu { cla: 0, ins: Verify, p1: 0, p2: 128, data: [ <<this is my pin :D>>] }
[TRACE yubikey::transaction] >>> [0, 32, 0, 128, 8, <<this is my pin :D>>]
[TRACE yubikey::apdu] <<< Response { status_words: Success, data: [] }
```
https://github.com/str4d/age-plugin-yubikey/blob/22fd00bd22ee8a8fe9f3b33db2e4b7eea944bf37/src/key.rs#L357
```
[TRACE yubikey::transaction] going to send 5 bytes in this go
[TRACE yubikey::apdu] >>> Apdu { cla: 0, ins: GetData, p1: 63, p2: 255, data: [92, 3, 95, 193, 9] }
[TRACE yubikey::transaction] >>> [0, 203, 63, 255, 5, 92, 3, 95, 193, 9]
[TRACE yubikey::apdu] <<< Response { status_words: Success, data: [83, 28, 136, 26, 137, 24, <<24-byte MgmKey>>] }
```
https://github.com/str4d/age-plugin-yubikey/blob/22fd00bd22ee8a8fe9f3b33db2e4b7eea944bf37/src/key.rs#L358
https://github.com/iqlusioninc/yubikey.rs/blob/23bbf1b783b575355ea5b21f1757826b46512320/src/yubikey.rs#L347-L351:
```rust
        // get a challenge from the card
        let challenge = Apdu::new(Ins::Authenticate)
            .params(ALGO_3DES, KEY_CARDMGM)
            .data([TAG_DYN_AUTH, 0x02, 0x80, 0x00])
            .transmit(&txn, 261)?;
```
```
[TRACE yubikey::apdu] >>> Apdu { cla: 0, ins: Authenticate, p1: 3, p2: 155, data: [124, 2, 128, 0] }
[TRACE yubikey::transaction] >>> [0, 135, 3, 155, 4, 124, 2, 128, 0]
[TRACE yubikey::apdu] <<< Response { status_words: IncorrectParamError, data: [] }
Error: Error while communicating with YubiKey: authentication error
```

So it appears that:
- Your YubiKey accepts the provided PIN (which is not the default PIN, so the change-PIN chunk of logic is skipped).
- Your YubiKey successfully returns the protected management key (required to generate a new key, stored inside the YubiKey, protected by your PIN).
- The returned management key is 24 bytes, indicating it should be a 3DES management key (we don't currently support AES).
- Your YubiKey rejects the first step of the management key authentication protocol (requesting a challenge), responding with `IncorrectParamError`.

Assuming that `IncorrectParamError` refers to the APDU parameters, these are `ALGO_3DES, KEY_CARDMGM`. The only way I can imagine these being incorrect is if the management key is not a 3DES management key. Can you confirm that your key uses a 3DES management key?

In the meantime, I'll try and figure out what the "canonical" error is for "wrong management key algorithm); if I can detect it, I can report a more useful error to the user (in the interim before #92 is implemented).

**Comment by str4d** [comment]
> Assuming that `IncorrectParamError` refers to the APDU parameters, these are `ALGO_3DES, KEY_CARDMGM`.

The `yubikey` crate documents `IncorrectParamError` as "Incorrect parameter in command data field", which would be `[TAG_DYN_AUTH, 0x02, 0x80, 0x00]`. So that suggests it's not a problem with the management key not being 3DES. All of these constants come from Yubico's `yubico-piv-tool`; I'll try and figure out what they mean.

**Comment by str4d** [comment]
Looks like `yubico-piv-tool` does the same thing (just changing `ALGO_3DES` if relevant): https://github.com/Yubico/yubico-piv-tool/blob/a72b2054de4b8ee0bf534edadd4de64d0ded92a9/lib/ykpiv.c#L983-L1003

**Comment by cpainchaud** [comment]
Hi,

 Yubikey Manager UI won't tell me if it's AES or 3DES but I am 99.9% sure I picked AES. Can I change change the mgmt key without loosing what's in there? The UI  doesn't warn me of any data loss/reset ....

**Comment by cpainchaud** [comment]
I have just changed it to 3DES (without any apparent loss of data) and it now works like a charm. May be you should warn users who are failing at this stage that 3DES is the only supported scheme.

By the way, thank you for your fantastic and didactic explanations!

**Comment by str4d** [comment]
Excellent! That suggests `IncorrectParamError` is the way to determine that the wrong management key type is being used. I can't access that status from outside the `yubikey` crate, so instead I'll just add a custom error around the `yubikey.authenticate(mgm_key)` call that says "hey, something failed here, it might be that you used an AES management key, which we don't currently support".

**Comment by str4d** [comment]
> * The returned management key is 24 bytes, indicating it should be a 3DES management key (we don't currently support AES).

In testing #139, I've figured out the last piece of the puzzle: you used AES-192 for the algorithm. which also uses a 24-byte management key. Had you used AES-128 or AES-256, it would have been the wrong length for TDES, the `yubikey` crate would have rejected it, and you'd instead have seen the (wrong but still useful) "Custom unprotected non-TDES management keys are unsupported" error message, instead of "authentication error".
