### ISSUE TITLE
Question: Will this replace OpenPGP keys?

### ISSUE THREAD

**Issue by YaroKasear** [str4d/age-plugin-yubikey#159]
I am thinking of using this to make my Yubikey just that much more secure, but I'm hesitant to use it.

Will this overwrite the OpenPGP keys I already have on my Yubikey(s) or will I be able to put my age identities on my Yubikey(s) without losing those keys I already have?

**Comment by str4d** [comment]
It should not. This plugin uses the YubiKey's PIV applet (and in particular, the "legacy" slots so it won't collide with any apps using the "main" slots), while the OpenPGP keys are presumably stored in the YubiKey's OpenPGP applet (but you would need to confirm that yourself).
