### ISSUE TITLE
Can age identities coexist with GPG?

### ISSUE THREAD

**Issue by andy-bell101** [str4d/age-plugin-yubikey#181]
Dumb question rather than an issue, but I can't actually find anything definitive anywhere online. I followed drduh's guide to set up my yubikey for GPG. Can I use this package to also add an age key to my yubikey? Or are they mutually exclusive?

**Comment by ZingyAwesome** [comment]
This plugin uses a PIV slot on a YubiKey which is separate from the GPG slots. You can have both on the same YubiKey at the same time.

**Comment by andy-bell101** [comment]
Thank you!
