### ISSUE TITLE
Timed out while waiting for a YubiKey to be inserted

### ISSUE THREAD

**Issue by honza** [str4d/age-plugin-yubikey#187]
## Environment

* OS:NixOS
* age-plugin-yubikey version: 0.5.0 (also latest from source)

## What were you trying to do

I ran the binary without arguments in order to set up a new yubikey.

## What happened

I received the following error:

```
⏳ Please insert the YubiKey you want to set up.

Error: Timed out while waiting for a YubiKey to be inserted.
```

`ykman` can see the yubikey without problems

PIV is enabled

```
$ ykman info
Device type: YubiKey 5C
Serial number: ---
Firmware version: 5.7.1
Form factor: Keychain (USB-C)
Enabled USB interfaces: OTP, FIDO, CCID

Applications
Yubico OTP  	Enabled
FIDO U2F    	Enabled
FIDO2       	Enabled
OATH        	Enabled
PIV         	Enabled
OpenPGP     	Enabled
YubiHSM Auth	Enabled
```

cc #156

**Comment by c0deaddict** [comment]
I'm also hitting this issue, it's caused by an update to `ccid` it seems: https://github.com/NixOS/nixpkgs/issues/349249
This PR fixes it for me: https://github.com/NixOS/nixpkgs/pull/350153

**Comment by honza** [comment]
Amazing, thanks @c0deaddict!
