### ISSUE TITLE
PIN Policy Ignored

### ISSUE THREAD

**Issue by nrdxp** [str4d/age-plugin-yubikey#34]
## Environment

* OS: NixOS
* age-plugin-yubikey version: 0.1.0

## What were you trying to do

I'm working on a PR to [agenix](https://github.com/ryantm/agenix) (ryantm/agenix#46) to add support for this plugin. 

## What happened
In order to make that viable, I set my generated identity's PIN policy to _never_, however, when I go to decrypt the files, it still asks for my PIN each time regardless.

```console
❯ command cat age-yubikey-identity.txt
#       Serial: 11300418, Slot: 2
#         Name: age identity ...
#      Created: Fri, 04 Jun 2021 03:22:04 +0000
#   PIN policy: Never  (A PIN is NOT required to decrypt)
# Touch policy: Never  (A physical touch is NOT required to decrypt)
# ...

❯ agenix -i age-yubikey-identity.txt -e aws.age
Enter PIN for YubiKey with serial 11300418:
```

Don't be confused by the use of agenix above, the same thing happens with rage as well (which agenix uses under the hood).

**Comment by nrdxp** [comment]
As additional information. I went ahead and verified the pin policy was in fact set properly by generating an attestation certificate and reading the relevant extension:
```
❯ openssl x509 -in 83.pem -text -certopt ext_dump -noout
            1.3.6.1.4.1.41482.3.8:
                0000 - 01 01
```
![image](https://user-images.githubusercontent.com/34083928/120905463-6a96aa00-c60f-11eb-81fd-2dd4af453318.png)

**Comment by str4d** [comment]
This is an artifact of the way I currently implement management key logic: the PIN is always requested on connection, so we can always handle the management key correctly.

This is the same underlying issue as #30; I'll fix them together.

**Comment by str4d** [comment]
#35 should fix this; LMK if it works for you!
