### ISSUE TITLE
[BUG] `yubikey-piv` has been renamed to yubikey

### ISSUE THREAD

**Issue by ModdedGamers** [str4d/age-plugin-yubikey#40]
## Environment

* OS: N/A
* age-plugin-yubikey version: 0.1

## What were you trying to do
INstall `age-plugin-yubikey`
## What happened

```
    Updating crates.io index
  Downloaded age-plugin-yubikey v0.1.0
  Downloaded 1 crate (34.6 KB) in 0.64s
  Installing age-plugin-yubikey v0.1.0
error: failed to compile `age-plugin-yubikey v0.1.0`, intermediate artifacts can be found at `/var/folders/dh/6d8rl8lj3nn5k73d6qkb982w0000gp/T/cargo-installg3snb9`

Caused by:
  no matching package named `yubikey-piv` found
  location searched: registry `crates-io`
  required by package `age-plugin-yubikey v0.1.0`
```

Please upload a 0.1.1 release depending on the `yubikey` library instead. The `yubikey-piv` library was yanked yesterday.

**Comment by str4d** [comment]
Hmm, that's annoying. @tarcieri was there a security reason for `yubikey-piv` being yanked?

In any case, #38 migrates us to `yubikey`. I was going to wait until a new `yubikey` release that included my `nom 7` PR, but given that no one can install `age-plugin-yubikey` anymore, I'll proceed with a release.
