### ISSUE TITLE
Clarify what kind of Yubikey is required in README.

### ISSUE THREAD

**Issue by vext01** [str4d/age-plugin-yubikey#42]
There are a few different kinds of yubikey and I'm unsure which is required for usage with age-plugin-yubikey.

For example I have one of those cheap github-branded ones somewhere. I know I can't use that one for storing gpg keys. I suppose I can't use it for age either? Can we say what is required in README?

Thanks.

**Comment by lowski** [comment]
I'm looking for a new Yubikey and I'd also like to know if the cheap blue ones are supported or if series 5 is required.

**Comment by lcmen** [comment]
@vext01 I think blue ones are not supported. When I run `age-plugin-yubikey`, it asks me to insert Yubikey I want to setup. Unfortunately when I plug in the Yubikey Security Key, it doesn't see it and eventually times out.

**Comment by colemickens** [comment]
The blue ones are FIDO2 only and this uses the PIV app, so that's about what I'd expect.

**Comment by str4d** [comment]
Yep, that's correct. Only PIV keys will work (but as a corollary, _any_ PIV keys will work, not just YubiKeys). I do note this already in the README, but we can make it more explicit for YubiKey versions; there aren't too many to list.
