### ISSUE TITLE
UX: Print message if Yubikey is waiting for touch

### ISSUE THREAD

**Issue by catleeball** [str4d/age-plugin-yubikey#44]
This might fit better in the Rage and/or Age repo; I don't really know exactly where/how this would be handled. Let me know and I can close this bug and reopen elsewhere if needed. :)

## What were you trying to do

Decrypt a file using an age key on my Yubikey

## What happened

Ran this to decrypt:

```
> cat test.txt.age | rage -d -i age-yk-id-20.txt > test.txt
```

Terminal sat quietly waiting for a Yubikey touch. It's easy to miss that it might be waiting for this, so it may be nice to print a message to the console when awaiting a key touch. E.g.:

```
> cat test.txt.age | rage -d -i age-yk-id-20.txt > test.txt
Awaiting Yubikey touch...
# user touches key, operation completes
> 
```

**Comment by str4d** [comment]
This is the right place for the issue 🙂

Could you please test #45 and check that it works for you?

**Comment by catleeball** [comment]
LGTM, built with the patch from #45 and it's working good on my end! Thank you for your hard work on rage and this plugin!  :)

```
> age-plugin-yubikey -g

Enter PIN for YubiKey with serial 123456 (default is 123456): [hidden]
👆 Please touch the YubiKey
```

**Comment by str4d** [comment]
After talking with @FiloSottile, we've decided to solve this issue in a different way: having the clients print a message if a plugin is slow. So I'll be removing the "Please touch the YubiKey" message I added in #45, and `rage 0.8` will handle it instead.
