### ISSUE TITLE
Question regarding generation of the shared secret with the YubiKey

### ISSUE THREAD

**Issue by fhilgers** [str4d/age-plugin-yubikey#49]
As I understand it, the main benefit of external hardware security keys like the YubiKey is that the private keys never leave the device. This does not prevent any encrypted data to be leaked, which could happen on every decryption, but it makes it impossible for they decryption keys to ever be compromised. To not expose the keys, decryption happens on the hardware token itself.

After looking through this implementation for using the YubiKey as age recipient, I was a bit confused as to how exactly this is achieved.

If I am not mistaken, a shared secret is derived from the private key located on the YubiKey: https://github.com/str4d/age-plugin-yubikey/blob/b3590f4ce1f570be34aa5d132840d4a7122c67b2/src/key.rs#L424-L432  

This private key obviously does not leave the device, but the generated shared secret is exposed and could be leaked when decrypting. So the shared secret should be different for every encryption/decryption for the same Yubikey recipient by generating some sort of salt and saving that in the header of the encrypted file. 

Is this how it is done or is there even a smarter way to do this? This information would be very useful regarding whether a similar implementation could be used to utilize Fido2 keys with hmac-secret extension as another form of age/rage recipient (for which I started a discussion https://github.com/FiloSottile/age/discussions/390).

Thank you for this plugin and also for the amazing work regarding age/rage in general!

**Comment by str4d** [comment]
> This private key obviously does not leave the device, but the generated shared secret is exposed and could be leaked when decrypting. So the shared secret should be different for every encryption/decryption for the same Yubikey recipient by generating some sort of salt and saving that in the header of the encrypted file.
>
> Is this how it is done or is there even a smarter way to do this?

The shared secret derived for a YubiKey recipient does not encrypt the file directly; it is only used to encrypt the file key, which is itself random bytes and is used to encrypt the file. So we're already in a situation where for each new file encryption, we're encrypting a different "message" (file key) to the YubiKey recipient.

Additionally, `age-plugin-yubikey` uses ephemeral-static ECDH internally. This is easier to spot on the encryption side:
https://github.com/str4d/age-plugin-yubikey/blob/b3590f4ce1f570be34aa5d132840d4a7122c67b2/src/format.rs#L104-L121

The `esk` value is randomly generated for each new file encryption. Assuming good RNG (which we need to assume anyway) the shared secret will therefore be different for each encryption to the same recipient. We can ignore collisions, as the P-256 scalar field is 256 bits, so the probability of collisions is around 2<sup>-128</sup>.

You are correct that we still need to be careful about how secrets are managed in-memory, as knowledge of the shared secret would allow decryption of that specific file. The return type of `decrypt_data` is [`yubikey::Buffer`](https://docs.rs/yubikey/0.5.0/yubikey/type.Buffer.html), which is defined to be self-zeroizing; likewise I use either the `secrecy` or `zeroize` crates as appropriate to manage secrets as best I can, and use constant-time operations (in this case, HKDF).
