### ISSUE TITLE
UX: plugin interface documentation

### ISSUE THREAD

**Issue by smlx** [str4d/age-plugin-yubikey#58]
## What were you trying to do

I'm interested in writing an age plugin along similar lines to `age-plugin-yubikey`.

## What happened

I searched but couldn't find any documentation on the plugin interface exposed by `rage` (and `age` at some point I guess).

It is possible to read the code and play around with `age-plugin-yubikey` to figure out how to implement an equivalent interface, but I wondered: is there any documentation on the plugin executable interface? For example: which commands or flags are required? which are optional? what are their arguments? what do they return? etc.

Does any documentation along those lines exist?

**Comment by str4d** [comment]
Yes! I'd been developing the age plugin spec in a HackMD, but it has now been moved to here: https://github.com/C2SP/C2SP/pull/5

I also implemented the `age-plugin` Rust crate (which this plugin uses), which handles all the IPC logic, so all you need to implement is the plugin logic.
