### ISSUE TITLE
Apple Silcon support

### ISSUE THREAD

**Issue by luedigernet** [str4d/age-plugin-yubikey#71]
Are there any plans to offer native Apple Silicon support?

**Comment by str4d** [comment]
There's no particular reason for not having support in the code. Providing release binaries OTOH would require having an Actions workflow for generating those binaries. GitHub doesn't yet provide M1 builders; hopefully cross-compilation from an Intel macOS machine would be sufficient to produce them.

I've recently acquired a native Apple Silicon device, so I can actually start testing the plugin on it to see what issues there might be.

**Comment by FiloSottile** [comment]
FWIW, the Homebrew build that I use (`brew install age-plugin-yubikey`) is a native Apple Silicon one, and works great!

**Comment by jason-yost-jamf** [comment]
Providing release binaries for Apple Silicon would be very nice.

**Comment by str4d** [comment]
I've made the release workflow changes that should produce valid M1 binaries. I'll test it with the 0.3.1 release, and make changes if necessary before 0.4.0.
