### ISSUE TITLE
"size error" generating a key on macOS 12.4

### ISSUE THREAD

**Issue by antifuchs** [str4d/age-plugin-yubikey#72]
## Environment

* OS: `macOS 12.4 (21F79)`
* age-plugin-yubikey version: `age-plugin-yubikey 0.3.0`

## What were you trying to do

I'm trying to generate an age key on my two yubikey 4c nanos' PIV slot. Each of the yubikeys has a GPG key stored on it, and each is connected to a different mac - one M1 max macbook pro, and one to an x86-64 macbook pro. The PINs are somewhere between 9 and 15 digits long (but only numerical). Neither successfully generates a key, reporting "size error".

## What happened

On the M1 max machine:

```
:;    age-plugin-yubikey -- --generate --name 'personal 4c'

Enter PIN for YubiKey with serial 6900832 (default is 123456): [hidden]
Error: Error while communicating with YubiKey: size error

[ Did this not do what you expected? Could an error be more useful? ]
[ Tell us: https://str4d.xyz/age-plugin-yubikey/report              ]
```

Same on the intel machine:

```
:;    ~/.cargo/bin/age-plugin-yubikey --generate --name 'work 4c'

Enter PIN for YubiKey with serial 15748267 (default is 123456): [hidden]
Error: Error while communicating with YubiKey: size error

[ Did this not do what you expected? Could an error be more useful? ]
[ Tell us: https://str4d.xyz/age-plugin-yubikey/report              ]
```

**Comment by str4d** [comment]
Per the PIV specifications:

> [...] the PIV Card Application PIN shall be between 6 and 8 bytes in length [...]

So a 9-15 digit numeric PIN will be too long, resulting in the `size error` you are encountering.

I'll close this issue once I have added a better error for this, either here or in the upstream `yubikey` crate.

**Comment by str4d** [comment]
> Each of the yubikeys has a GPG key stored on it, and each is connected to a different mac - one M1 max macbook pro, and one to an x86-64 macbook pro. The PINs are somewhere between 9 and 15 digits long (but only numerical).

Are the PINs you're referring to the ones you already use for GPG? You'll need to set a different PIN in that case for the PIV applet. Try using the default PIN 123456 (which is likely unaltered from factory default, and in any case the PIV applet is likely empty if you've never used it before).

**Comment by antifuchs** [comment]
Oh man, I feel extra silly now for assuming the PIV pin and the GPG pin were the same. Using the PINs that age-plugin-yubikey suggests (and sticking to 6 digits) works, thanks so much!
