### ISSUE TITLE
UX: Needed to install pcscd on Ubuntu

### ISSUE THREAD

**Issue by divergentdave** [str4d/age-plugin-yubikey#83]
## What were you trying to do

Install and run `age-plugin-yubikey` on an Ubuntu desktop OS.

## What happened

```
$ age-plugin-yubikey --list-all
Error: Error while communicating with YubiKey: PC/SC error
Cause: The Smart card resource manager is not running
```

## Solution

I resolved this by running `sudo apt-get install pcscd`. (I also had to install `libpcsclite-dev` previously to satisfy a compile-time dependency)

**Comment by str4d** [comment]
There are two things we can do here:
- Note in the documentation that Linux systems usually require you to separately install the PCSC server (c/f e.g. Windows which has it built in).
- Detect this particular error code, and transform it into a more useful error that suggests a solution to the user.
